<?php

namespace Database\Seeders;

use App\Models\PelangganReseller;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PelangganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pelanggan = [
            [
                'nama' => '3 Putra Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Sutoyo 5 No  140',
                    'kecamatan'=>'Banjar Barat',
                    'kelurahan'=>'Teluk Dalam',
                    'kota'=>'Banjarmasin',
                    'provinsi'=>'Kalimantan Selatan',
                    'pulau'=>'Kalimantan',
                    'short'=>'Banjarmasin',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Sutoyo 5 No  140", "Kel. Teluk Dalam, Kec. Banjar Barat", "Banjarmasin"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082253633222',
                    ]
                ],
                'initial' => '3PM',
            ], [
                'nama' => 'Akong',
                'alamat' => [[
                    'jalan'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Jakarta Utara',
                    'kabupaten'=>null,
                    'provinsi'=>'DKI Jakarta',
                    'pulau'=>'Jawa',
                    'short'=>'Pluit, Jakarta',
                    'negara'=>'Indonesia',
                    'long'=>'["Pluit, Jakarta"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081291200168',
                    ]
                ],
                'initial' => 'AK',
                'is_reseller' => 'no',
            ], [
                'nama' => 'Abadi Motor',
                'alamat' => [[
                    'jalan'=>'Permata 1 No 366',
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pangkalpinang',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Permata 1, No 366", "Pangkalpinang - Bangka"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ABA',
                'reseller' => 'Akong'
            ], [
                'nama' => 'Acun Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pangkalpinang',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Pangkalpinang, Bangka"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ACUN',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Ade Jok Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Tangerang',
                    'provinsi'=>'Banten',
                    'pulau'=>'Jawa',
                    'short'=>'Tangerang',
                    'negara'=>'Indonesia',
                    'long'=>'["Tangerang, Banten, Indonesia"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ADE',
            ], [
                'nama' => 'Ajung Jaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Pasar Lama',
                    'kecamatan'=>'Sentani',
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Jayapura',
                    'provinsi'=>null,
                    'pulau'=>'Papua',
                    'short'=>'Sentani, Jayapura',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Pasar Lama", "Depan Gereja Zoar", "Sentani, Jayapura"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08124886092',
                    ]
                ],
                'initial' => 'AJ',
            ], [
                'nama' => 'Alindo SM',
                'alamat' => [[
                    'jalan'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>null,
                    'provinsi'=>'DKI Jakarta',
                    'pulau'=>'Jawa',
                    'negara'=>'Indonesia',
                    'short'=>'Jakarta',
                    'long'=>'["Jakarta"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ALI',
            ], [
                'nama' => 'Andi MC',
                'alamat' => [[
                    'jalan'=>null,
                    'desa'=>'Karanggan',
                    'kecamatan'=>'Gn. Putri',
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Bogor',
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'negara'=>'Indonesia',
                    'short'=>'Karanggan',
                    'long'=>'["Jakarta"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ANDI',
            ], [
                'nama' => 'Andri',
                'nama_bisnis' => 'Millenium Motor',
                'sapaan' => 'Bpk.',
                'alamat' => [[
                    'jalan'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Bukittinggi',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Barat',
                    'pulau'=>'Sumatra',
                    'negara'=>'Indonesia',
                    'short'=>'Bukittinggi',
                    'long'=>'["Ambil di gudang, Bukittinggi"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081363619119',
                    ]
                ],
                'initial' => 'MIL2',
            ], [
                'nama' => 'Angian Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pangkalpinang',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Pangkalpinang, Bangka"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ANG',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Asia Pasifik',
                'alamat' => [[
                    'jalan'=>'Jl. Serdam',
                    'komplek'=>'Komplek Pesona Alam No E7',
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Serdam", "Komplek Pesona Alam No E7", "Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08125732345',
                    ]
                ],
                'initial' => 'ASPA',
            ], [
                'nama' => 'B2 Saddle',
                'alamat' => [[
                    'jalan'=>'Jl. Ion Martasasmita KM 02',
                    'desa'=>'Rancasari',
                    'kecamatan'=>'Pamanukan',
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Subang',
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'short'=>'Pamanukan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Ion Martasasmita KM 02", "DS Rancasari, Kec. Pamanukan (RM. Rosin)", "Kab. Subang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082126106000',
                    ]
                ],
                'initial' => 'B2',
            ], [
                'nama' => 'BCC Variasi',
                'alamat' => [[
                    'jalan'=>'Jl. Otista No 8',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Sukabumi',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'short'=>'Sukabumi',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Otista No 8", "Sukabumi"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08127037093',
                    ]
                ],
                'initial' => 'BCC',
            ], [
                'nama' => 'Bengkel Apang',
                'alamat' => [[
                    'jalan'=>'Jl. Otista No 8',
                    'desa'=>null,
                    'kecamatan'=>'Tanjung Pandan',
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Belitung',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Bangka',
                    'negara'=>'Indonesia',
                    'long'=>'["Pasar Pagi Samping Surau", "Tj. Pandan, Belitung"]',
                ]],
                'no_kontak' => null,
                'initial' => 'BENG',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Benteng Motor',
                'alamat' => [[
                    'jalan'=>'Jl. GG Bulu Sarang No 151',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["JL. GG Bulu Sarang No 151", "Makassar"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0411',
                        'nomor'=>'3622019',
                    ]
                ],
                'initial' => 'BEN',
            ], [
                'nama' => 'Berjaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Selat Panjang No A1',
                    'desa'=>null,
                    'kecamatan'=>'Pontianak Utara',
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Selat Panjang No A1", "Pontianak Utara"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'085389999188',
                    ]
                ],
                'initial' => 'BER',
            ], [
                'nama' => 'Biran Motor',
                'alamat' => [[
                    'jalan'=>'Semabung Baru No 50',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pangkalpinang',
                    'kabupaten'=>'Belitung',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Semabung Baru No 50", "Pangkalpinang - Bangka"]',
                ]],
                'no_kontak' => null,
                'initial' => 'BIR',
                'reseller' => 'Akong',
            ], [
                'nama' => 'BSM',
                'alamat' => [[
                    'jalan'=>'Jl. Gading Indah Utara 4/20',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Gading Indah Utara 4/20", "(masuk dari Perumahan Gading Regency)", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08125732345',
                    ]
                ],
                'initial' => 'BSM',
            ], [
                'nama' => 'Budi Stiker',
                'alamat' => [[
                    'jalan'=>'Jl. Mesjid No 126',
                    'desa'=>null,
                    'kecamatan'=>'Medan Barat',
                    'kelurahan'=>'Kesawan',
                    'kota'=>'Medan',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Utara',
                    'pulau'=>'Sumatra',
                    'short'=>'Medan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Mesjid No 126", "Kesawan - Medan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'061',
                        'nomor'=>'4572651',
                    ]
                ],
                'initial' => 'BS',
            ], [
                'nama' => 'Cendana Mega Pratama (CMP)',
                'bentuk' => 'CV',
                'alamat' => [[
                    'jalan'=>'Jl. H. Yunus Yanis No 62',
                    'desa'=>null,
                    'kecamatan'=>'Jelutung',
                    'kelurahan'=>'Kebun Handil',
                    'kota'=>'Jambi',
                    'kabupaten'=>null,
                    'provinsi'=>'Jambi',
                    'pulau'=>'Sumatra',
                    'short'=>'Jambi',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. H. Yunus Yanis No 62", "Kebun Handil, Jambi"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081366911999',
                    ]
                ],
                'initial' => 'CMP',
            ], [
                'nama' => 'Central Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'komplek'=>'Perumahan Ambon Bay Regency No A30',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Ambon',
                    'kabupaten'=>null,
                    'provinsi'=>'Maluku',
                    'pulau'=>'Ambon',
                    'short'=>'Ambon',
                    'negara'=>'Indonesia',
                    'long'=>'["Perumahan Ambon Bay Regency No A30", "Sebelah Dealer Hino Lateri - Ambon"]',
                ]],
                'no_kontak' => null,
                'initial' => 'CEN',
                'reseller'=>'Akong',
            ], [
                'nama' => 'Central Young Hero',
                'alamat' => [[
                    'jalan'=>'Jl. Sindansana No 27',
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Singkawang',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Singkawang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Sindansana No 27", "Singkawang"]',
                ]],
                'no_kontak' => null,
                'initial' => 'HERO',
            ], [
                'nama' => 'Champion Motor',
                'alamat' => [[
                    'jalan'=>'Jl. DI Panjaitan No 16-17',
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Jambi',
                    'kabupaten'=>null,
                    'provinsi'=>'Jambi',
                    'pulau'=>'Sumatra',
                    'short'=>'Jambi',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. DI Panjaitan No 16,17", "Jambi"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08788017017',
                    ]
                ],
                'initial' => 'CHA',
            ], [
                'nama' => 'Christovel',
                'alamat' => [[
                    'jalan'=>'Jl. Diponegoro No 66',
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Wenang',
                    'kelurahan'=>'Mahakeret Barat',
                    'kota'=>'Manado',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Utara',
                    'pulau'=>'Sulawesi',
                    'short'=>'Manado',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Diponegoro No 66", "Mahakeret Barat, Manado"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082192515555',
                    ]
                ],
                'initial' => 'CHRIS',
            ], [
                'nama' => 'Darwis Motor',
                'alamat' => [[
                    'jalan'=>'Poros Pallangga Goa',
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["Poros Pallangga Goa", "Makassar"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081244255038',
                    ]
                ],
                'initial' => 'DWIS',
            ], [
                'nama' => 'Dunia Variasi',
                'alamat' => [[
                    'jalan'=>'Jl. Raya Dupak No 63',
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Raya Dupak No 63", "Blok D No 18, Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08164387388',
                    ]
                ],
                'initial' => 'DV',
            ], [
                'nama' => 'DV Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Nilam 5',
                    'rt'=>'07','rw'=>'03',
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Bukit Intan',
                    'kelurahan'=>'Bacang',
                    'kota'=>'Pangkalpinang',
                    'kabupaten'=>'Belitung',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Nilam 5, RT07/RW03", "Kel.Bacang,Kec.Bukit Intan", "Pangkalpinang, Bangka"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082184492070',
                    ]
                ],
                'initial' => 'DVM',
            ], [
                'nama' => 'Fortuner Motor',
                'nama2' => '- G -',
                'alamat' => [[
                    'jalan'=>'Jl. K.H. Agus Salim No 344',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Gorontalo',
                    'kabupaten'=>null,
                    'provinsi'=>'Gorontalo',
                    'pulau'=>'Sulawesi',
                    'short'=>'Gorontalo',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. K.H Agus Salim No 344", "KM 4,5, Gorontalo"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'085399950500',
                    ]
                ],
                'initial' => 'FOR',
            ], [
                'nama' => "Fortuner Motor",
                'nama2' => "- L -",
                'alamat' => [[
                    'jalan'=>'Jl. Muhammad Hatta No 79',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>'Maahas',
                    'kecamatan'=>'Luwuk',
                    'kelurahan'=>'Maahas',
                    'kota'=>null,
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Tengah',
                    'pulau'=>'Sulawesi',
                    'short'=>'Luwuk',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Muhammad Hatta No 79", "Maahas, Luwuk, Sulteng"]',
                ]],
                'no_kontak' => null,
                'initial' => 'FOR',
            ], [
                'nama' => 'Endang',
                'sapaan' => 'Bpk.',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Tangerang',
                    'kabupaten'=>null,
                    'provinsi'=>'Banten',
                    'pulau'=>'Jawa',
                    'short'=>'Tangerang',
                    'negara'=>'Indonesia',
                    'long'=>'["Tangerang, Banten"]',
                ]],
                'no_kontak' => null,
                'initial' => null,
            ], [
                'nama' => 'Garuda Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Tudopuli 10, BLOK K-5 No 29',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>'Komplek Puri Taman Sari',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["Komplek Puri Taman Sari", "Jl. Tudopuli 10, BLOK K-5 No 29", "Makassar"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081355438758',
                    ]
                ],
                'initial' => 'GAR',
            ], [
                'nama' => 'Global Stiker',
                'alamat' => [[
                    'jalan'=>'Jl. Jendral Sudirman No 207',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Palembang',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Selatan',
                    'pulau'=>'Sumatra',
                    'short'=>'Palembang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Jendral Sudirman No 207", "Palembang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0711',
                        'nomor'=>'9199977',
                    ]
                ],
                'initial' => 'GLO',
            ], [
                'nama' => 'Hadi Rumawan',
                'sapaan' => 'Bpk.',
                'alamat' => [[
                    'jalan'=>'Jl. Golf, GG Karet 2 No 73',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Landasan Ulin',
                    'kelurahan'=>null,
                    'kota'=>'Banjarbaru',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Selatan',
                    'pulau'=>'Kalimantan',
                    'short'=>'Banjarbaru',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Golf, GG Karet 2 No 73", "Landasan Ulin Banjarbaru", "Kalimantan Selatan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081351588351',
                    ]
                ],
                'initial' => 'HADI',
            ], [
                'nama' => 'Harapan Baru',
                'alamat' => [[
                    'jalan'=>'Jl. Cipto Mangunkusumo',
                    'rt'=>'13','rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>'Harapan Baru',
                    'kecamatan'=>'Loa Janan Ilir',
                    'kota'=>'Samarinda',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Timur',
                    'pulau'=>'Kalimantan',
                    'short'=>'Samarinda',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Cipto Mangunkusumo RT:13", "Harapan Baru, Kec. Loa Janan Ilir", "Samarinda"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082149065389',
                    ]
                ],
                'initial' => 'HAR',
            ], [
                'nama' => 'Hokky Motor',
                'alamat' => [[
                    'jalan'=>'Jl. R Wolter Monginsidi No 131',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>'Bahu',
                    'kecamatan'=>'Malalayang',
                    'kota'=>'Manado',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Utara',
                    'pulau'=>'Sulawesi',
                    'short'=>'Manado',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. R Wolter Monginsidi No 131", "Bahu - Manado"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'085319782288',
                    ]
                ],
                'initial' => 'HOK',
            ], [
                'nama' => 'HR Jaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Gatot Subroto No 21',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Samarinda',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Timur',
                    'pulau'=>'Kalimantan',
                    'short'=>'Samarinda',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Gatot Subroto No 21", "Samarinda"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082111522998',
                    ]
                ],
                'initial' => 'HR',
            ], [
                'nama' => 'H.S Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Veteran Simpang SMP 7 No 42',
                    'rt'=>'31','rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Banjarmasin',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Selatan',
                    'pulau'=>'Kalimantan',
                    'short'=>'Banjarmasin',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Veteran Simpang SMP 7", "No 42, RT:31, Banjarmasin"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08125036074',
                    ]
                ],
                'initial' => 'HS',
            ], [
                'nama' => 'IKB Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Kenjeran 281',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Kenjeran 281", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081331992290',
                    ]
                ],
                'initial' => 'HS',
            ], [
                'nama' => 'Indah Motor',
                'alamat' => [[
                    'jalan'=>'Jl. MS Rahman 95',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Pangkalpinang',
                    'kabupaten'=>'Belitung',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. MS Rahman 95", "Pangkalpinang, Bangka"]',
                ]],
                'no_kontak' => null,
                'initial' => 'INDH',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Indo Putra Mandiri',
                'alamat' => [[
                    'jalan'=>'Jl. Bandang XII No 1',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Bandang XII No 1", "Makassar"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08124208300',
                    ]
                ],
                'initial' => 'IPM',
            ], [
                'nama' => 'Ismail',
                'nama' => 'Bpk.',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>'Citeureup',
                    'kota'=>null,
                    'kabupaten'=>'Bogor',
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'short'=>null,
                    'negara'=>'Indonesia',
                    'long'=>'["Citeureup"]',
                ]],
                'no_kontak' => null,
                'initial' => 'IS',
            ], [
                'nama' => 'Izur Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Teluk Tiram',
                    'rt'=>'21','rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Banjarmasin',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Selatan',
                    'pulau'=>'Kalimantan',
                    'short'=>'Banjarmasin',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Teluk Tiram", "GG. Raden No 15, RT:21", "Banjarmasin"]',
                ]],
                'no_kontak' => null,
                'initial' => 'IZ',
            ], [
                'nama' => 'Jaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Sam Ratulangi No 123',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Manado',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Utara',
                    'pulau'=>'Sulawesi',
                    'short'=>'Manado',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Sam Ratulangi No 123", "Manado"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0431',
                        'nomor'=>'862550',
                    ]
                ],
                'initial' => 'JAYMO',
            ], [
                'nama' => 'Jaya Queen Stiker',
                'alamat' => [[
                    'jalan'=>'Jl. ST Syahrir No 63',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Bukittinggi',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Barat',
                    'pulau'=>'Sumatra',
                    'short'=>'Bukittinggi',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. ST Syahrir No 63", "Bukittinggi"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081372798121',
                    ]
                ],
                'initial' => 'JAYQU',
            ], [
                'nama' => 'Jaya Stiker',
                'alamat' => [[
                    'jalan'=>'Jl. Mesjid No 47',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Medan',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Utara',
                    'pulau'=>'Sumatra',
                    'short'=>'Medan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Mesjid No 47", "Medan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081397129261',
                    ]
                ],
                'initial' => 'JAYST',
            ], [
                'nama' => 'Jhon Motor',
                'alamat' => [[
                    'jalan'=>'Jl. GG Bulu Sarang Blok C No 13',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>'Komplek Bulu Sarang Square',
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. GG Bulu Sarang Blok C No 13", "Komplek Bulu Sarang Square, Makassar"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0411',
                        'nomor'=>'3651559',
                    ]
                ],
                'initial' => 'JHON',
            ], [
                'nama' => 'Joy Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Tumpangsari No 52 B',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>'Cakranegara',
                    'kota'=>'Mataram',
                    'kabupaten'=>null,
                    'provinsi'=>'Nusa Tenggara Barat',
                    'kodepos'=>'83235',
                    'pulau'=>'Lombok',
                    'short'=>'Lombok',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Tumpangsari No 52 B", "Cakranegara, Lombok"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081238213131',
                    ]
                ],
                'initial' => 'JOY',
            ], [
                'nama' => 'Kalbar Motoshop',
                'alamat' => [[
                    'jalan'=>'Jl. Agus Salim No 7',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Samarinda',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Timur',
                    'pulau'=>'Kalimantan',
                    'short'=>'Samarinda',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Agus Salim No 7", "Samarinda"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081280886008',
                    ]
                ],
                'initial' => 'KAL',
            ], [
                'nama' => 'Kanaka Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Valanda Maramis No 194',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Manado',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Utara',
                    'pulau'=>'Sulawesi',
                    'short'=>'Manado',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Valanda Maramis No 194", "Manado"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0431',
                        'nomor'=>'851441',
                    ]
                ],
                'initial' => 'KAN',
            ], [
                'nama' => 'Karunia Jaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Parit Pangeran',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Parit Pangeran", "Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081250102997',
                    ]
                ],
                'initial' => 'KAR',
            ], [
                'nama' => 'Karya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Jurung No 6',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Medan',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Utara',
                    'pulau'=>'Sumatra',
                    'short'=>'Medan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Jurung No 6", "Simpang Wahidin, Medan"]',
                ]],
                'no_kontak' => null,
                'initial' => 'KAR',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Kencana Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Jayapura',
                    'provinsi'=>null,
                    'pulau'=>'Papua',
                    'short'=>'Jayapura',
                    'negara'=>'Indonesia',
                    'long'=>'["Papua, Jayapura"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'085254280807',
                    ]
                ],
                'initial' => 'KENCA',
            ], [
                'nama' => 'KMS Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Jendral Sudirman No 47 D',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Palembang',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Selatan',
                    'pulau'=>'Sumatra',
                    'short'=>'Palembang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Jendral Sudirman No 47 D", "Palembang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>'0711',
                        'nomor'=>'7081681',
                    ]
                ],
                'initial' => 'KMS',
            ], [
                'nama' => 'Kolongan Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Martadinata 3',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Manado',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Utara',
                    'pulau'=>'Sulawesi',
                    'short'=>'Manado',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Martadinata 3", "Manado"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'085256125992',
                    ]
                ],
                'initial' => 'KOL',
            ], [
                'nama' => 'Leo Speedshop',
                'alamat' => [[
                    'jalan'=>'Ruko No 5, Jl.Kartama',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>'Komplek Royal Kartama Residence',
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>'Marpoyan Damai',
                    'kota'=>'Pekanbaru',
                    'kabupaten'=>null,
                    'provinsi'=>'Riau',
                    'pulau'=>'Sumatra',
                    'short'=>'Pekanbaru',
                    'negara'=>'Indonesia',
                    'long'=>'["Komplek Royal Kartama Residence", "Ruko No 5, Jl.Kartama (Samping SMPN 2)","Marpoyan Damai, Pekanbaru"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081298284688',
                    ]
                ],
                'initial' => 'KMS',
            ], [
                'nama' => 'Millenium Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Mayor Ruslan No 1333 F',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Palembang',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Selatan',
                    'pulau'=>'Sumatra',
                    'short'=>'Palembang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Mayor Ruslan No 1333 F", "Palembang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0711',
                        'nomor'=>'362262',
                    ]
                ],
                'initial' => 'MIL',
            ], [
                'nama' => 'Mitra Jaya Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Baubau',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Tenggara',
                    'pulau'=>'Buton',
                    'short'=>'Baubau',
                    'negara'=>'Indonesia',
                    'long'=>'["Baubau", "Sulawesi Tenggara"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081233469951',
                    ]
                ],
                'initial' => 'MIJA',
            ], [
                'nama' => 'Mitra Usaha Mandiri',
                'alamat' => [[
                    'jalan'=>'Jl. Sepakat 2',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>'Komplek Mutiara Villa Sepakat, No B3',
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Sepakat 2", " Ruko Mutiara Villa Sepakat, No B3", "Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082153210278',
                    ]
                ],
                'initial' => 'MUM',
            ], [
                'nama' => 'Mulya Sandi',
                'alamat' => [[
                    'jalan'=>'Jl. Riau Ujung',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Pekanbaru',
                    'kabupaten'=>null,
                    'provinsi'=>'Riau',
                    'pulau'=>'Sumatra',
                    'short'=>'Pekanbaru',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Riau Ujung", "Pekanbaru"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'081314082897',
                    ]
                ],
                'initial' => 'MUL',
            ], [
                'nama' => 'Mustika Raya',
                'alamat' => [[
                    'jalan'=>'Jl. Mesjid No 124 B',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Medan',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Utara',
                    'pulau'=>'Sumatra',
                    'short'=>'Medan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Mesjid No 124 B", "Medan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'061',
                        'nomor'=>'4579659',
                    ]
                ],
                'initial' => 'MUS',
            ], [
                'nama' => 'Mutiara Motor Mandiri',
                'bentuk' => 'CV',
                'alamat' => [[
                    'jalan'=>'Jl. Simpang Panji Suroso 160',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Malang',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Malang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Simpang Panji Suroso 160", "Malang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'0818387233',
                    ]
                ],
                'initial' => 'MUT',
            ], [
                'nama' => 'Nagata Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Wirapati No 15',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>'Sintang',
                    'kota'=>'Sintang',
                    'kabupaten'=>'Sintang',
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Sintang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Wirapati No 15", "Sintang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08125602566',
                    ]
                ],
                'initial' => 'NA',
            ], [
                'nama' => 'NGK Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Panjaitan No 5,6,7',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Jelutung',
                    'kelurahan'=>'Kebun Handil',
                    'kota'=>'Jambi',
                    'kabupaten'=>null,
                    'provinsi'=>'Jambi',
                    'pulau'=>'Sumatra',
                    'short'=>'Jambi',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Panjaitan No 5,6,7", "Kebun Handil - Jambi"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'082373566066',
                    ]
                ],
                'initial' => 'NGK',
            ], [
                'nama' => 'Nino Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Kyai Tambak Deres 141',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Kyai Tambak Deres 141", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'085100585253',
                    ]
                ],
                'initial' => 'NINO',
            ], [
                'nama' => 'Novi',
                'sapaan' => 'Ibu',
                'alamat' => [[
                    'jalan'=>'A8/ROY/HSES/SRW/HSES',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>null,
                    'provinsi'=>null,
                    'pulau'=>null,
                    'short'=>'Malaysia',
                    'negara'=>'Malaysia',
                    'long'=>'["A8/ROY/HSES/SRW/HSES", "Malaysia"]',
                ]],
                'no_kontak' => null,
                'initial' => 'NOV',
            ], [
                'nama' => 'Nurmanto',
                'alamat' => [[
                    'jalan'=>'Jl. Perdamaian, Pal IX',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>'Kubu Raya',
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Toko Mulia Makmur", "Jl. Perdamaian, Pal IX, Kubu Raya/Ujung", "Kota Baru Pontianak"]',
                ]],
                'no_kontak' => null,
                'initial' => 'NURM',
            ], [
                'nama' => 'Nusi Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Lahat',
                    'provinsi'=>'Sumatra Selatan',
                    'pulau'=>'Sumatra',
                    'short'=>'Lahat',
                    'negara'=>'Indonesia',
                    'long'=>'["Lahat", "Sumatra Selatan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>'Dodi',
                        'nomor'=>'085266220856',
                    ]
                ],
                'initial' => 'NUS',
                'ktrg' => null,
                'reseller' => 'Akong',
            ], [
                'nama' => 'Pasti Sukses Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Sutorejo Utara Baru No 3',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Sutorejo Utara Baru No 3", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081330186448',
                    ]
                ],
                'initial' => 'PAS',
            ], [
                'nama' => 'Pedoman Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Gusti Hamzah No 93',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Sambas',
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Sambas',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Gusti Hamzah No 93", "Sambas"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'08125607439',
                    ]
                ],
                'initial' => 'PE',
            ], [
                'nama' => 'Pelita Jok',
                'alamat' => [[
                    'jalan'=>'Jl. Pelita Gg 3, No 52',
                    'rt'=>'39','rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Sungai Pinang',
                    'kelurahan'=>'Sungai Pinang Dalam',
                    'kota'=>'Samarinda',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Timur',
                    'pulau'=>'Kalimantan',
                    'short'=>'Sambas',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Pelita Gg 3, No 52, RT:39", "Sungai Pinang Dalam", "Kec. Sungai Pinang, Samarinda"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'082154221345',
                    ]
                ],
                'initial' => 'PEL',
            ], [
                'nama' => 'Pioneer Jaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Rumambi No 9',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Manado',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Utara',
                    'pulau'=>'Sulawesi',
                    'short'=>'Manado',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Rumambi No 9", "Manado"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>'0431',
                        'nama'=>null,
                        'nomor'=>'865088',
                    ]
                ],
                'initial' => 'PION',
            ], [
                'nama' => 'Prospek Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>'Komplek Bumi Batara 2',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Komplek Bumi Batara 2", "BLOK C, No 58, Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'08125794675',
                    ]
                ],
                'initial' => 'PROS',
            ], [
                'nama' => 'Rajawali Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Parit Lalang No 1',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pangkalpinang',
                    'kabupaten'=>'Belitung',
                    'provinsi'=>'Kepulauan Bangka Belitung',
                    'pulau'=>'Bangka',
                    'short'=>'Pangkalpinang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Parit Lalang No 1", "Pangkalpinang, Bangka"]',
                ]],
                'no_kontak' => null,
                'initial' => 'RAJ',
            ], [
                'nama' => 'Rama Motor',
                'alamat' => [[
                    'jalan'=>"Jl. Imam Bonjol No 38 B",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Samarinda',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Timur',
                    'pulau'=>'Kalimantan',
                    'short'=>'Samarinda',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Imam Bonjol No 38 B", "Samarinda"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081350340369',
                    ]
                ],
                'initial' => 'RAM',
            ], [
                'nama' => 'Sambung Jaya Motor',
                'alamat' => [[
                    'jalan'=>"Jl. Imam Bonjol No 426",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Imam Bonjol No 426", "Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081256735233',
                    ]
                ],
                'initial' => 'SAM',
            ], [
                'nama' => 'Saudara Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Jakarta',
                    'kabupaten'=>null,
                    'provinsi'=>'DKI Jakarta',
                    'pulau'=>'Jawa',
                    'short'=>'Jakarta',
                    'negara'=>'Indonesia',
                    'long'=>'["Jakarta"]',
                ]],
                'no_kontak' => null,
                'initial' => 'SAU',
            ], [
                'nama' => 'Scopa Motor',
                'alamat' => [[
                    'jalan'=>"Jl. Kalimantan No 23",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Praya',
                    'kelurahan'=>null,
                    'kota'=>'Mataram',
                    'kabupaten'=>null,
                    'provinsi'=>'Nusa Tenggara Barat',
                    'pulau'=>'Lombok',
                    'short'=>'Lombok',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Kalimantan No 23", "Mataram, Lombok"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>0370,
                        'nama'=>null,
                        'nomor'=>'636414',
                    ]
                ],
                'initial' => 'SCO',
            ], [
                'nama' => 'Sejati Jaya Sondy',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["Makassar", "Sulawesi Selatan"]',
                ]],
                'no_kontak' => null,
                'initial' => 'SON',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Setia Budi',
                'alamat' => [[
                    'jalan'=>"Jl. Jendral A. Yani KM6,7",
                    'rt'=>'14','rw'=>null,
                    'komplek'=>"Komplek Bun Yamin Pemain 1, Raya Utama No 9",
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Banjarmasin',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Selatan',
                    'pulau'=>'Kalimantan',
                    'short'=>'Banjarmasin',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Jendral A. Yani KM6,7", "Komplek Bun Yamin Pemain 1, Raya Utama", "No 9, RT:14, Banjarmasin"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081348191028',
                    ]
                ],
                'initial' => 'SET',
            ], [
                'nama' => 'Sinar Perkasa Motor',
                'alamat' => [[
                    'jalan'=>"Jl. Pasar 3",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>"Komplek Sehati Indah No 88 FF",
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Medan',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Utara',
                    'pulau'=>'Sumatra',
                    'short'=>'Medan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Pasar 3", "Komplek Sehati Indah No 88 FF", "Daerah Krakatau, Medan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081396005859',
                    ]
                ],
                'initial' => 'SIN',
            ], [
                'nama' => 'SS Uji 169 Handil Bakti',
                'alamat' => [[
                    'jalan'=>"Jl. Karya Sabumi IV No 26 A",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Banjarmasin',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Selatan',
                    'pulau'=>'Kalimantan',
                    'short'=>'Banjarmasin',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Karya Sabumi IV No 26 A", "Kayu Tangi, Banjarmasin"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>0561,
                        'nama'=>null,
                        'nomor'=>'3303216',
                    ]
                ],
                'initial' => 'SS',
            ], [
                'nama' => 'Sukses Makmur Motor',
                'alamat' => [[
                    'jalan'=>"Jl. PM NOOR",
                    'rt'=>'39','rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Samarinda',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Timur',
                    'pulau'=>'Kalimantan',
                    'short'=>'Samarinda',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. PM NOOR, RT:39", "Samarinda"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081347777722',
                    ]
                ],
                'initial' => 'SM',
            ], [
                'nama' => 'Sumber Abadi Motor',
                'alamat' => [[
                    'jalan'=>"KM 14",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>null,
                    'provinsi'=>null,
                    'pulau'=>'Sumatra',
                    'short'=>null,
                    'negara'=>'Indonesia',
                    'long'=>'["KM 14 Jambi-Palembang"]',
                ]],
                'no_kontak' => null,
                'initial' => 'SAM',
                'reseller' => 'Akong',
            ], [
                'nama' => 'Sumber Cemerlang',
                'alamat' => [[
                    'jalan'=>"Jl. Karet 24 Ilir",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>"Bukit Kecil",
                    'kelurahan'=>null,
                    'kota'=>'Palembang',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Selatan',
                    'pulau'=>'Sumatra',
                    'short'=>'Palembang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Karet 24 Ilir", "Kec. Bukit Kecil, Palembang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'087891607875',
                    ]
                ],
                'initial' => 'SUMC',
            ],[
                'nama' => 'Sumber Makmur',
                'alamat' => [[
                    'jalan'=>"Kapasari V No 11",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Kapasari V No 11", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081234725210',
                    ]
                ],
                'initial' => 'SUMAK',
            ], [
                'nama' => 'Sumber Mandiri Motor',
                'alamat' => [[
                    'jalan'=>"Jl. Ringin Sari No 8,9",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Ringin Sari No 8,9", "(samping Alfamart Ringinsari), Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'0811578278',
                    ]
                ],
                'initial' => 'SUMAN',
            ], [
                'nama' => 'Sumber Rejeki Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>null,
                    'provinsi'=>'DKI Jakarta',
                    'pulau'=>'Jawa',
                    'short'=>'Jakarta',
                    'negara'=>'Indonesia',
                    'long'=>'["Jakarta"]',
                ]],
                'no_kontak' => null,
                'initial' => 'SUMRE',
            ], [
                'nama' => 'Surya Jaya Motor',
                'alamat' => [[
                    'jalan'=>"Jl. IR. H. Juanda No 54-56",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>null,
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Pontianak',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. IR. H. Juanda No 54-56", "Pontianak"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081256562985',
                    ]
                ],
                'initial' => 'SJM',
            ], [
                'nama' => 'Surya Perdana Agung',
                'alamat' => [[
                    'jalan'=>'Jl. Soekarno Hatta',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>'Komplek Sentral Niaga No 12, A-B',
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Pekanbaru',
                    'kabupaten'=>null,
                    'provinsi'=>'Riau',
                    'pulau'=>'Sumatra',
                    'short'=>'Pekanbaru',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Soekarno Hatta", "Komplek Sentral Niaga No 12, A-B", "Pekanbaru"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'08127501178',
                    ]
                ],
                'initial' => 'SPA',
            ], [
                'nama' => 'Teratai Motor',
                'alamat' => [[
                    'jalan'=>"Jl. KL. Yos Sudarso 8J,8K,8L",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>"Komplek Brayan One Stop Square",
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Medan',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Utara',
                    'pulau'=>'Sumatra',
                    'short'=>'Medan',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. KL. Yos Sudarso 8J,8K,8L", "Komplek Brayan One Stop Square", "Medan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>'061',
                        'nama'=>null,
                        'nomor'=>'6643002',
                    ]
                ],
                'initial' => 'TER',
            ], [
                'nama' => 'Toko 86',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Bogor',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'short'=>'Cibinong',
                    'negara'=>'Indonesia',
                    'long'=>'["Cibinong]',
                ]],
                'no_kontak' => null,
                'initial' => 'T86',
            ], [
                'nama' => 'Tommy',
                'sapaan' => 'Ko',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Depok',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'short'=>'Depok',
                    'negara'=>'Indonesia',
                    'long'=>'["Depok]',
                ]],
                'no_kontak' => null,
                'initial' => 'TOM',
            ], [
                'nama' => 'Top Variasi',
                'alamat' => [[
                    'jalan'=>"Jl. Jendral Sudirman No 52 E",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Palembang',
                    'kabupaten'=>null,
                    'provinsi'=>'Sumatra Selatan',
                    'pulau'=>'Sumatra',
                    'short'=>'Palembang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Jendral Sudirman No 52 E", "Palembang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0711',
                        'nama'=>null,
                        'nomor'=>'357936',
                    ]
                ],
                'initial' => 'TOP',
            ], [
                'nama' => 'Tulank',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Bogor',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Barat',
                    'pulau'=>'Jawa',
                    'short'=>'Cibinong',
                    'negara'=>'Indonesia',
                    'long'=>'["Cibinong]',
                ]],
                'no_kontak' => null,
                'initial' => 'TL',
            ], [
                'nama' => 'UD Mitra',
                'alias'=>null,
                'alamat' => [[
                    'jalan'=>"Jl.Kendangsari, Blok O, No 5",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl.Kendangsari, Blok O, No 5", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081231338838',
                    ]
                ],
                'initial' => 'UDM',
            ], [
                'nama' => 'UD Mitra',
                'alias'=>'Agung Jaya Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Poros Palangga, Jl. KH. Wahid Hasyim 187',
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Gowa',
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Gowa',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Poros Palangga", "Jl. KH. Wahid Hasyim 187", "Kab. Gowa, Sulawesi Selatan"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081231338838',
                    ]
                ],
                'initial' => 'UDM',
            ], [
                'nama' => 'UD Serba Jaya',
                'alamat' => [[
                    'jalan'=>"Jl. Raya Tembok Dukuh No 134 A",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Surabaya',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Surabaya',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Raya Tembok Dukuh No 134 A", "Surabaya"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nama'=>null,
                        'nomor'=>'081330301567',
                    ]
                ],
                'initial' => 'UDS',
            ], [
                'nama' => 'WA',
                'alamat' => [[
                    'jalan'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>'Makassar',
                    'kabupaten'=>null,
                    'provinsi'=>'Sulawesi Selatan',
                    'pulau'=>'Sulawesi',
                    'short'=>'Makassar',
                    'negara'=>'Indonesia',
                    'long'=>'["Makassar"]',
                ]],
                'initial' => 'WA',
            ], [
                'nama' => 'WK Motor',
                'alamat' => [[
                    'jalan'=>"Jl. Seliung No 10",
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>'Sungai Pinyuh',
                    'kelurahan'=>null,
                    'kota'=>'Pontianak',
                    'kabupaten'=>'Mempawah',
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Sei Pinyuh',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Seliung No 10", "Sei Pinyuh, Kalimantan Barat"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'kantor',
                        'kodearea'=>'0561',
                        'nama'=>null,
                        'nomor'=>'652483',
                    ]
                ],
                'initial' => 'WK',
            ], [
                'nama' => 'Yensen',
                'alamat' => [[
                    'jalan'=>null,
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>null,
                    'provinsi'=>'DKI Jakarta',
                    'pulau'=>'Jawa',
                    'short'=>'Jakarta',
                    'negara'=>'Indonesia',
                    'long'=>'["Jakarta"]',
                ]],
                'no_kontak' => null,
                'initial' => 'YEN',
            ], [
                'nama' => 'Zen Motor',
                'alamat' => [[
                    'jalan'=>'Jl. Simpang Panji Suroso 160',
                    'rt'=>null,'rw'=>null,
                    'komplek'=>null,
                    'desa'=>null,
                    'kelurahan'=>null,
                    'kecamatan'=>null,
                    'kota'=>'Malang',
                    'kabupaten'=>null,
                    'provinsi'=>'Jawa Timur',
                    'pulau'=>'Jawa',
                    'short'=>'Malang',
                    'negara'=>'Indonesia',
                    'long'=>'["Jl. Simpang Panji Suroso 160", "(Jalan Keluar Mikrolet Arjosari)", "Malang"]',
                ]],
                'no_kontak' => [
                    [
                        'tipe'=>'seluler',
                        'kodearea'=>null,
                        'nomor'=>'0818387233',
                    ]
                ],
                'initial' => 'ZEN',
            ], [
                'nama' => 'Zona Motor',
                'alamat' => [[
                    'jalan'=>null,
                    'komplek'=>null,
                    'kecamatan'=>null,
                    'kelurahan'=>null,
                    'kota'=>null,
                    'kabupaten'=>'Ketapang',
                    'provinsi'=>'Kalimantan Barat',
                    'pulau'=>'Kalimantan',
                    'short'=>'Ketapang',
                    'negara'=>'Indonesia',
                    'long'=>'["Ketapang, Kalimantan Barat"]',
                ]],
                'no_kontak' => null,
                'initial' => 'ZON',
            ],
        ];

        for ($i = 0; $i < count($pelanggan); $i++) {
            DB::table('pelanggans')->insert([
                'nama' => $pelanggan[$i]['nama'],
                'alamat' => json_encode($pelanggan[$i]['alamat']),
                'no_kontak' => $pelanggan[$i]['no_kontak'],
                'pulau_id' => $pelanggan[$i]['pulau_id'],
                'daerah_id' => $pelanggan[$i]['daerah_id'],
                'initial' => $pelanggan[$i]['initial'],
            ]);
        }

    }
}
